Aviva.FizzBuzz/Models/FizzBuzzModel.cs
namespace Aviva.FizzBuzz.Models
{
    using Interface;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class FizzBuzzModel
    {
        [Required]
        [Display(Name = "Please enter the number")]
        [Range(1, 1000, ErrorMessage = "Please enter a value between 1 and 1000")]
        public int? Number { get; set; }

        public List<IFizzBuzz> FizzBuzzList { get; set; }
    }
}
    

Aviva.FizzBuzz/Controllers/FizzBuzzController.cs
namespace Aviva.FizzBuzz.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using Aviva.FizzBuzz.Interface;
    using Aviva.FizzBuzz.Models;

    public class FizzBuzzController : Controller
    {
        private readonly IBusinessRules _businessrules;
        private readonly IList<IFizzBuzz> _fizzbuzz;

        public FizzBuzzController(IBusinessRules businessRules, IList<IFizzBuzz> fizzBuzz)
        {
            _businessrules = businessRules;
            _fizzbuzz = fizzBuzz;
        }

        public ActionResult FizzBuzzView()
        {
            return View("FizzBuzzView", new FizzBuzzModel());
        }

        [HttpPost]
        public ActionResult GetData(FizzBuzzModel postModel)
        {
            var objData = new FizzBuzzModel {Number = postModel.Number};
            if (ModelState.IsValid) FillFizzBuzzList(objData);

            return View("FizzBuzzView", objData);
        }

        private void FillFizzBuzzList(FizzBuzzModel objData)
        {
            if (objData.Number != null) objData.FizzBuzzList = _businessrules.GetData(objData.Number.Value, _fizzbuzz);
        }
    }
}

Aviva.FizzBuzz/Views/FizzBuzz/FizzBuzzView.cshtml
@model Aviva.FizzBuzz.Models.FizzBuzzModel

@{
    ViewBag.Title = "FizzBuzz Application";
}

<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
@using (Html.BeginForm("getData", "FizzBuzz"))
{
    <div>
        <fieldset>
            <table>
                <tr>
                    <td>
                        <div class="editor-label">
                            @Html.LabelFor(m => m.Number)
                        </div>
                    </td>
                    <td>
                        <div class="editor-field">
                            @Html.TextBoxFor(m => m.Number)
                            @Html.ValidationMessageFor(m => m.Number)
                        </div>
                    </td>
                    <td>
                        <input type="submit" name="DisplayList" value="Display List" class="button"/>
                    </td>
                </tr>
            </table>
        </fieldset>
    </div>

    if (Model.FizzBuzzList != null && Model.FizzBuzzList.Count > 0)
    {
        <div id="DvGrid">
            <fieldset>
                <table id="Grid">
                    <thead>
                    <tr>
                        <th> Output </th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach (var number in Model.FizzBuzzList)
                    {
                        <tr>
                            @if (string.IsNullOrEmpty(number.MessageColor))
                            {
                                <td class="@number">@number.Message</td>
                            }
                            else
                            {
                                <td style="color: @number.MessageColor" class="@number">@number.Message</td>
                            }

                        </tr>
                    }
                    </tbody>
                </table>
            </fieldset>
        </div>
    }
}
</body>
</html>

Aviva.FizzBuzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {

            $('#Grid').dataTable({
                "pagingType": "simple",
                "ordering": false,
                "info": false,
                "Grid_length": false,
                "lengthChange": false,
                "pageLength": 20,
                "searching": false
            });
        });
    </script>
</body>
</html>